Zhwa
gdsc-ncku/Unity-GG pull request #27
Opened 2024-12-17 11:19 UTC by z-hwa

為修改以及新增的腳本添加註解
整理commit

2024-12-19 03:56 UTC, Aka2210 approved these changes

2024-12-19 03:56 UTC, Aka2210 commented on Assets/Scripts/Items and drops/Items/Reducer.cs
> +        EventManager.TriggerEvent<float>(NameOfEvent.TimeControl, slowdownFactor);
若已經打算使用UniRx插件，那訂閱事件也建議改成使用較方便的UniRx設置

2024-12-19 03:56 UTC, Aka2210 commented on Assets/Scripts/Manager/EventManager.cs
> +/// 事件管理器
應該改成說明運作邏輯，否則這邊極為難讀

2024-12-19 03:56 UTC, Aka2210 commented on Assets/Scripts/Manager/TimeManager.cs
> +/// �x���C������ɶ��������ƪ�
註解全變亂碼了

2024-12-19 03:57 UTC, Aka2210 approved these changes

2024-12-19 03:57 UTC, Aka2210 approved these changes

2024-12-19 03:57 UTC, Aka2210 approved these changes

2024-12-19 03:57 UTC, Aka2210 approved these changes

2024-12-19 03:59 UTC, Aka2210 requested changes
基本上問題在EventManager跟reducer.cs裡面，主要是因為要將原始的unity事件用法改為UniRx所以應該需要重構，然後EventManager跨越容易跨越多個scripts被使用，註解方面建議寫得更完整，並且架構時考慮可讀性(題外話我覺得多型可讀性極差，還是少用好了XDD)。

2024-12-19 04:03 UTC, Aka2210 reviewed
Player Move方式的改變尚有疑慮，playerRigibody.MovePosition可能導致移動效果不佳，待討論、測試

2024-12-19 04:25 UTC, Aka2210 requested changes
掉落物和道具上層沒問題，但下層觸發的方式可以改用更方便的插件

2024-12-19 04:25 UTC, Aka2210 commented on Assets/Scripts/Controller/PlayerMove.cs
> +            playerRigibody.MovePosition(playerRigibody.position + moveDistance * deltaTime);
可能會導致移動效果不怪異，待討論

2024-12-19 04:25 UTC, Aka2210 commented on Assets/Scripts/Controller/PlayerMove.cs
> +
事件觸發方式重構後要回來改

2024-12-19 04:25 UTC, Aka2210 commented on Assets/Scripts/Items and drops/Items/Reducer.cs
> +        EventManager.TriggerEvent<bool>(NameOfEvent.ChangeMoveMode, false);
若已經打算使用UniRx插件，那訂閱事件也建議改成使用較方便的UniRx設置

2024-12-19 04:25 UTC, Aka2210 commented on Assets/Scripts/Items and drops/Items/Reducer.cs
> +        EventManager.TriggerEvent<bool>(NameOfEvent.ChangeMoveMode, true);
重構事件觸發方式後要記得回來改

2024-12-19 04:25 UTC, Aka2210 commented on Assets/Scripts/Manager/EventManager.cs
> +}
需要被重構，使用UniRx可以簡化很多東西，這邊的多型我看到快裂開ㄌ

2024-12-19 04:25 UTC, Aka2210 commented on Assets/Scripts/Manager/TimeManager.cs
> +    }
事件重構後要回來改

2024-12-19 04:26 UTC, z-hwa commented
> Player Move方式的改變尚有疑慮，playerRigibody.MovePosition可能導致移動效果不佳，待討論、測試

這裡是因為如果不改成用MovePosition
用原本的運動方式 更換time.deltatime以及time.unscaledDeltaTime的話
在時間流速等於1的情況下 移動速度會不同

比如說使用減速器後玩家的移動速度在理想設計中應該保持一致
但如果使用原本的移動方式 會變慢一些
不知道甚麼原因

2024-12-19 06:48 UTC, z-hwa commented
重構了事件系統
為玩家移動添加摩擦力
把一些中文亂碼的地方改回正確的中文

2024-12-19 08:59 UTC, Aka2210 reviewed
剩變數重複問題~

2024-12-19 08:59 UTC, Aka2210 commented on Assets/Scripts/Controller/PlayerMove.cs
> +            Vector3 targetVelocity = moveDir * maxSpeed;
簡化參數，上方有moveDirection，也可以這邊自己設moveDir，留一個就好

2024-12-25 02:47 UTC, Aka2210 approved these changes

2024-12-25 02:48 UTC, merged